name: Build Application
run-name: ${{ github.actor }} is running build
on: 
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  run-build:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller

      # Step 5: Create the executable with PyInstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name sjj main.py

            # Step 6: Upload the build artifact (optional)
      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sjj
          path: dist/sjj
          # Step 6: Upload the executable to the created release
      - name: Upload executable as release asset
        run: |
          RELEASE_ID=$(jq --raw-output .release.id $GITHUB_EVENT_PATH)
          FILE_PATH=dist/sjj  # Path to your executable
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @$FILE_PATH \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=sjj"

      
