name: Build Application
run-name: ${{ github.actor }} is running build
on: 
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  run-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'ssj'
          options: --onefile, -- name "ssj", --console,

      - name: Upload Asset to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/ssj.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
