name: Build Application
run-name: ${{ github.actor }} is running build
on: 
  release:
    types:
      - published

jobs:
  run-build:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This is a job that runs on release"

